Added header design for a Become a parner page
mojnp/mojnp pull request #46
Opened 2023-06-24 10:16 UTC by Alen-Kalac

Added initial design for header and rough design of a body for a "Become a partner page".

2023-06-25 13:36 UTC, edinmavric requested changes
Use scss nesting logic, that's why we use scss, and use react-router-dom in App, revert index.css from app.css, and rename them to scss files to, i think that header should be outside of the Form too

2023-06-25 14:18 UTC, edinmavric requested changes

2023-06-25 14:18 UTC, edinmavric commented on partners/src/components/header/style.scss
Kill's the point of implementing scss

2023-06-25 14:18 UTC, edinmavric commented on partners/src/components/header/index.tsx
We don't know if this is header of Form, or header of Page?

2023-06-25 14:18 UTC, edinmavric commented on partners/src/index.css
Delete content from App.scss, and store it here, rename it to index.scss too

2023-06-25 14:18 UTC, edinmavric commented on partners/src/App.css
Delete content

2023-06-25 14:18 UTC, edinmavric commented on partners/src/App.tsx
implement react-router-dom with Footer and Header outside out of routes

2023-06-26 12:36 UTC, hamzaplojovic commented
Amazing work, just like we requested. We talked about the font, I am sure you will implement that very soon. As for the inputs: `business name`, `email`, safe `password` input with password strength check, `phone number`, textarea input for `description`, and a file input for the `logo`. For now, these are the ones we will be using, and we can add more inputs as organization schema scales to more features, like input for certifications, staff members, open jobs, and business locations around the town, but for now, these highlighted ones are enough. Thank you!

2023-06-26 12:37 UTC, hamzaplojovic requested changes
Great job, just fill out the content of the page with the form with inputs we requested in the comment

2023-07-02 11:43 UTC, hamzaplojovic approved these changes
Great job!

2023-07-02 11:43 UTC, merged